# Configuration file for Retina Image Analysis project
# This file contains default settings and hyperparameters

# Data Configuration
data:
  image_size: 512
  batch_size: 32
  num_workers: 4
  train_split: 0.7
  val_split: 0.15
  test_split: 0.15
  
  # Data augmentation parameters
  augmentation:
    rotation_range: 15
    zoom_range: 0.1
    horizontal_flip: true
    vertical_flip: false
    brightness_range: [0.8, 1.2]
    contrast_range: [0.8, 1.2]

# Model Configuration
model:
  architecture: "resnet50"  # Options: resnet50, efficientnet, densenet, custom_cnn
  pretrained: true
  num_classes: 5  # Number of disease classes + normal
  dropout_rate: 0.5
  
  # Model-specific parameters
  resnet:
    layers: [3, 4, 6, 3]
  
  efficientnet:
    compound_coeff: 0  # B0 to B7

# Training Configuration
training:
  epochs: 100
  learning_rate: 0.001
  optimizer: "adam"  # Options: adam, sgd, rmsprop
  weight_decay: 0.0001
  momentum: 0.9  # For SGD
  
  # Learning rate scheduling
  scheduler:
    type: "reduce_on_plateau"  # Options: reduce_on_plateau, cosine, step
    patience: 10
    factor: 0.5
    min_lr: 1e-7
  
  # Early stopping
  early_stopping:
    patience: 15
    min_delta: 0.001
    monitor: "val_loss"
  
  # Loss function
  loss:
    type: "cross_entropy"  # Options: cross_entropy, focal_loss, weighted_cross_entropy
    class_weights: null  # Will be calculated automatically if null

# Evaluation Configuration
evaluation:
  metrics:
    - accuracy
    - precision
    - recall
    - f1_score
    - auc_roc
    - confusion_matrix
  
  # Threshold for binary classification
  threshold: 0.5

# Inference Configuration
inference:
  batch_size: 16
  tta: false  # Test Time Augmentation
  ensemble: false
  confidence_threshold: 0.8

# Logging and Monitoring
logging:
  level: "INFO"
  save_logs: true
  log_dir: "./logs"
  
  # MLflow configuration
  mlflow:
    experiment_name: "retina_analysis"
    run_name: null  # Will be auto-generated if null
    tracking_uri: "http://localhost:5000"
  
  # Weights & Biases configuration
  wandb:
    project: "retina-image-analysis"
    entity: null
    tags: ["retina", "medical-imaging", "classification"]

# Paths
paths:
  data_root: "./data"
  raw_data: "./data/raw"
  processed_data: "./data/processed"
  annotations: "./data/annotations"
  models: "./models"
  checkpoints: "./checkpoints"
  logs: "./logs"
  results: "./results"

# Hardware Configuration
hardware:
  device: "auto"  # Options: auto, cpu, cuda, mps
  mixed_precision: true
  num_gpus: 1
  
# API Configuration
api:
  host: "localhost"
  port: 8000
  workers: 4
  reload: false
  log_level: "info"
  
  # CORS settings
  cors:
    allow_origins: ["*"]
    allow_methods: ["GET", "POST"]
    allow_headers: ["*"]

# Security
security:
  max_file_size: 10485760  # 10MB in bytes
  allowed_extensions: [".jpg", ".jpeg", ".png", ".tiff", ".bmp"]
  rate_limit: "100/minute"
